### ISSUE TITLE
关于适配Trss-Yunzai的建议

### ISSUE THREAD

**Issue by Strawxg** [Walkersifolia/mc-wiki#1]
[TRSSYz][19:18:44.025][MARK] example/mcwiki.js 缺少依赖：icqq
[TRSSYz][19:18:44.025][MARK] 新增插件后请执行安装命令：pnpm install -P 安装依赖
[TRSSYz][19:18:44.025][MARK] 如安装后仍未解决可联系插件作者将 icqq 依赖添加至插件的package.json dependencies中，或手工安装依赖

trss崽无法识别icqq依赖，请问后期是否有适配的计划？
![a42bcc357fc0f15702537c36c244bee5](https://github.com/Walkersifolia/mc-wiki/assets/127127787/a43cc68c-4045-4a8d-aa4b-89a216374c6a)

**Comment by S-t-e-v-e-e** [comment]
> [TRSSYz][19:18:44.025][MARK] example/mcwiki.js 缺少依赖：icqq [TRSSYz][19：18：44.025][MARK] 新增插件后请执行安装命令：pnpm install -P 安装依赖 [TRSSYz][19：18：44.025][MARK] 如安装后仍未解决可联系插件作者将 icqq 依赖添加至插件的package.json dependencies中，或手动安装依赖
> 
> trss崽无法识别icqq依赖，请问后期是否有适配的计划？ ![a42bcc357fc0f15702537c36c244bee5](https://user-images.githubusercontent.com/127127787/256979867-a43cc68c-4045-4a8d-aa4b-89a216374c6a.jpeg)

代码中删除import { segment } from 'icqq';

**Comment by Strawxg** [comment]
> > [TRSSYz][19:18:44.025][MARK] example/mcwiki.js 缺少依赖：icqq [TRSSYz][19：18：44.025][MARK] 新增插件后请执行安装命令：pnpm install -P 安装依赖 [TRSSYz][19：18：44.025][MARK] 如安装后仍未解决可联系插件作者将 icqq 依赖添加至插件的package.json dependencies中，或手动安装依赖
> > trss崽无法识别icqq依赖，请问后期是否有适配的计划？ ![a42bcc357fc0f15702537c36c244bee5](https://user-images.githubusercontent.com/127127787/256979867-a43cc68c-4045-4a8d-aa4b-89a216374c6a.jpeg)
> 
> 代码中删除import { segment } from 'icqq';

好的
